### ISSUE TITLE
Oddzielenie testów jednostkowych od integracyjnych

### ISSUE THREAD

**Issue by Marcin99b** [Blogplace/Blogplace.Backend#33]
Codecov może nam dawać osobne pokrycie dla różnych rodzajów testów. Potrzebujemy osobnych plików z pokryciem kodu. Najprościej zastąpić Blogplace.Tests dwoma projektami - Blogplace.Tests.Unit i Blogplace.Tests.Integration

W workflows/dotnet.yml będziemy musieli przekazywać dwa pliki, zamiast
- ./Blogplace.Tests/coverage.opencover.xml
będziemy mieć
- ./Blogplace.Tests.Unit/coverage.opencover.xml
- ./Blogplace.Tests.Integration/coverage.opencover.xml

W ich dokumentacji jest taki przykład
```yaml
steps:
- uses: actions/checkout@main
- uses: codecov/codecov-action@v4
  with:
    fail_ci_if_error: true # optional (default = false)
    files: ./coverage1.xml,./coverage2.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    token: ${{ secrets.CODECOV_TOKEN }} # required
    verbose: true # optional (default = false)
```
